image: Visual Studio 2015

branches:
  only:
    - master

build: off

install:
  - ps: $App = Start-Process -FilePath java -ArgumentList "-jar ./artiifacts/app-ibank-build-for-testers.jar" -PassThru

build_script:
  - ps: ./gradlew test --info "-Dselenide.headless=true"

on_finish:
  - ps: Stop-Process -Id $App.Id